/**
 * Writes supabase/seed.sql (genres, draft movements, Eric's starter plan) and
 * supabase/seed.test.sql (test clinician + VBTEST code) from content/seed.ts, so the database
 * and the app's built-in data never drift. Run after editing content/seed.ts:  pnpm db:seed:gen
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { GENRES, MOVEMENTS, STARTER_PROGRAMS, TEST_CLINICIAN, TEST_PROGRAMS, type SeedProgram } from "../content/seed";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const j = (v: unknown) => (v == null ? "null" : `${q(JSON.stringify(v))}::jsonb`);
const movementId = (slug: string) => {
  const mv = MOVEMENTS.find((m) => m.slug === slug);
  if (!mv) throw new Error(`unknown movement ${slug}`);
  return mv.id;
};

function programSql(p: SeedProgram): string[] {
  const out = [
    `insert into public.programs (id, clinician_id, code, name, clinic_name, clinic_phone, therapist_note, days_per_week, reviewed_by_eric) values (${q(p.id)}, ${q(p.clinicianId)}, ${q(p.code)}, ${q(p.name)}, ${q(p.clinicName)}, ${q(p.clinicPhone)}, ${q(p.therapistNote)}, ${p.daysPerWeek}, ${p.reviewedByEric}) on conflict (id) do nothing;`,
  ];
  p.sessions.forEach((s, si) => {
    out.push(`insert into public.program_sessions (id, program_id, name, sort, est_minutes) values (${q(s.id)}, ${q(p.id)}, ${q(s.name)}, ${si + 1}, ${s.estMinutes}) on conflict (id) do nothing;`);
    s.blocks.forEach((b, bi) =>
      out.push(
        `insert into public.session_blocks (id, program_session_id, movement_id, sort, sets, reps, hold_seconds, band_color, anchor) values (${q(b.id)}, ${q(s.id)}, ${q(movementId(b.movementSlug))}, ${bi + 1}, ${n(b.sets)}, ${n(b.reps)}, ${n(b.holdSeconds)}, ${q(b.bandColor)}, ${j(b.anchor)}) on conflict (id) do nothing;`,
      ),
    );
  });
  return out;
}

const seed: string[] = [
  "-- GENERATED by `pnpm db:seed:gen` from content/seed.ts. Do not edit by hand.",
  "-- Placeholder content: every movement and the starter plan are reviewed_by_eric = false,",
  "-- so production hides them until Eric reviews them.",
  "",
  "insert into public.genres (id, slug, name, clinical_name, description, sort) values",
  GENRES.map((g) => `  (${q(g.id)}, ${q(g.slug)}, ${q(g.name)}, ${q(g.clinicalName)}, ${q(g.description)}, ${g.sort})`).join(",\n") +
    "\non conflict (id) do update set slug = excluded.slug, name = excluded.name, clinical_name = excluded.clinical_name, description = excluded.description, sort = excluded.sort;",
  "",
  "insert into public.movements (id, genre_id, name, slug, level, board_models, needs_band, needs_handrail, needs_chair, default_anchor, video_url, poster_url, cues, safety_note, default_sets, default_reps, default_hold_seconds, reviewed_by_eric) values",
  MOVEMENTS.map((m) => {
    const g = GENRES.find((x) => x.slug === m.genreSlug)!;
    return `  (${q(m.id)}, ${q(g.id)}, ${q(m.name)}, ${q(m.slug)}, ${m.level}, ${arr(m.boardModels)}, ${m.needsBand}, ${m.needsHandrail}, ${m.needsChair}, ${j(m.defaultAnchor)}, ${q(m.videoUrl)}, ${q(m.posterUrl)}, ${arr(m.cues)}, ${q(m.safetyNote)}, ${n(m.defaultSets)}, ${n(m.defaultReps)}, ${n(m.defaultHoldSeconds)}, ${m.reviewedByEric})`;
  }).join(",\n") + "\non conflict (id) do nothing;",
  "",
  "-- Seated and easier alternatives (set after every movement exists).",
  ...MOVEMENTS.filter((m) => m.seatedAlternativeId || m.easierAlternativeId).map(
    (m) => `update public.movements set seated_alternative_id = ${q(m.seatedAlternativeId)}, easier_alternative_id = ${q(m.easierAlternativeId)} where id = ${q(m.id)};`,
  ),
  "",
  ...STARTER_PROGRAMS.flatMap(programSql),
  "",
];

const test: string[] = [
  "-- GENERATED by `pnpm db:seed:gen` from content/seed.ts. Do not edit by hand.",
  "-- TEST FIXTURE: one clinician and the VBTEST code, for the code -> plan -> session ->",
  "-- completion -> adherence round trip. Load into local or preview databases only, NEVER",
  "-- production. The address is on example.com, so no magic link can ever be delivered for it.",
  "",
  `insert into auth.users (id, email) values (${q(TEST_CLINICIAN.id)}, ${q(TEST_CLINICIAN.email)}) on conflict (id) do nothing;`,
  `insert into public.clinicians (id, display_name, clinic_name) values (${q(TEST_CLINICIAN.id)}, ${q(TEST_CLINICIAN.displayName)}, ${q(TEST_CLINICIAN.clinicName)}) on conflict (id) do nothing;`,
  "",
  ...TEST_PROGRAMS.flatMap(programSql),
  "",
];

const dir = path.join(process.cwd(), "supabase");
writeFileSync(path.join(dir, "seed.sql"), seed.join("\n"));
writeFileSync(path.join(dir, "seed.test.sql"), test.join("\n"));
console.log(`✓ wrote supabase/seed.sql (${GENRES.length} genres, ${MOVEMENTS.length} movements, ${STARTER_PROGRAMS.length} starter plan) and supabase/seed.test.sql (test clinician, ${TEST_PROGRAMS.map((p) => p.code).join(", ")})`);
